/**
 * Single runtime token layer measured from read-only Figma
 * `uMo04w9bgrchWXXDgO4W62` (Компоненты + phone frames ~390).
 * Screen aliases map Figma values onto one semantic object.
 */
export const designTokens = {
  color: {
    canvas: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceWarm: '#FFFFFF',
    surfaceMuted: '#F3F3F3',
    surfaceStrong: '#E8E8E8',
    surfacePanel: '#F3F3F3',
    searchSurface: '#F3F3F3',
    dialogSurface: '#FFFFFF',
    ink: '#2A2A2A',
    inkSoft: '#2A2A2A',
    textSecondary: '#8A8A8A',
    textMuted: '#8A8A8A',
    tabInactive: '#565656',
    textSubdued: '#565656',
    border: '#DEDEDE',
    borderStrong: '#2A2A2A',
    divider: '#E2E2E2',
    chip: 'rgba(0, 0, 0, 0.15)',
    chipOutline: 'rgba(255, 255, 255, 0.16)',
    placeholder: '#8A8A8A',
    action: '#292929',
    actionHover: '#000000',
    accent: '#E9401A',
    accentDark: '#E9401A',
    accentSoft: '#F3F3F3',
    success: '#039600',
    warning: '#A66B12',
    danger: '#FF0000',
    dangerHover: '#C40000',
    error: '#FF0000',
    focus: '#004DFF',
    overlay: 'rgba(41, 41, 41, 0.70)',
    overlayScrim: 'rgba(0, 0, 0, 0.70)',
    glass: 'rgba(255, 255, 255, 0.60)',
    glassStrong: 'rgba(255, 255, 255, 0.80)',
    glassChip: 'rgba(255, 255, 255, 0.70)',
    glassBorder: '#DEDEDE',
    glassBorderEnd: '#F3F3F3',
    atmosphereWash: 'rgba(255, 255, 255, 0.40)',
    modalDimmer: 'rgba(42, 42, 42, 0.50)',
    headerControl: '#F3F3F3',
    solid: '#292929',
    solidHover: '#000000',
    solidDisabled: '#949494',
    muted: '#8A8A8A',
    fieldHoverBorder: '#535353',
    ghostHover: '#F7F7F7',
    mutedFill: '#F3F3F3',
    mutedHover: '#E8E8E8',
    quietFill: '#EFEFEF',
    quietBorderStart: '#FFFFFF',
    quietBorderEnd: '#999999',
    textSubtle: '#6F6F6F',
    fieldHoverFill: '#FCFCFC',
    pressRing: 'rgba(0, 235, 151, 0.25)',
    saleLive: '#E9401A',
    saleAnnounce: '#51E91A',
    white: '#FFFFFF',
  },
  space: {
    x1: 4,
    x2: 8,
    x3: 12,
    x4: 16,
    x5: 20,
    x6: 24,
    x7: 28,
    x8: 32,
    x9: 36,
    x10: 40,
    x12: 48,
    x14: 56,
    x16: 64,
    x20: 80,
    // Figma 10/4 with an inside 1px stroke; the border adds the last pixel.
    chipX: 9,
    chipY: 3,
    chipGap: 4,
    choiceChipX: 10,
    choiceChipY: 8,
    buttonX: 16,
    buttonY: 8,
    quietButtonX: 14,
    quietButtonY: 8,
    quietButtonGap: 6,
    authorRowGap: 2,
    editorialGap: 4,
    fieldX: 12,
    fieldY: 13,
    fieldGap: 4,
    fieldErrorGap: 3,
    iconPad: 2,
    buttonIconPad: 4,
    coverPad: 12,
    coverGap: 8,
    coverBlockGap: 4,
    dockPad: 14,
    dockGap: 20,
    dockIconPad: 6,
    pageGutter: 12,
    sectionGap: 20,
    identityGap: 10,
    atmosphereOffset: 36,
    logoTop: 54,
    creatorCompactTop: 44,
    creatorCompactAtmosphereTop: -340,
    logoGap: 34,
    authorIdentityGap: 6,
    authorSectionGap: 18,
    authorHeaderBottom: 40,
    authorAboutGap: 26,
    authorChipX: 16,
    authorChipY: 5,
    authorChipGap: 10,
    workChipX: 12,
    workChipY: 5,
    workChipGap: 6,
    socialGroupX: 8,
    socialGroupY: 6,
    socialGroupGap: 12,
    filterOptionY: 9,
    headerIconHitSlop: 9,
  },
  radius: {
    small: 12,
    control: 18,
    compact: 18,
    image: 24,
    media: 24,
    card: 24,
    button: 80,
    panel: 24,
    aboutPanel: 12,
    dialog: 24,
    menu: 18,
    sheet: 28,
    pill: 999,
    field: 18,
    chip: 28,
    cover: 24,
    authorCover: 28,
    overlay: 12,
    dock: 200,
    avatar: 100,
    social: 30,
    achievement: 20,
    shareSheet: 20,
    workGallery: 20,
    statusDot: 20,
    filterSort: 14,
    filterCheckbox: 6,
    filterRadio: 20,
  },
  size: {
    achievementWidth: 266,
    shareQr: 164,
    touch: 44,
    input: 52,
    control: 36,
    button: 44,
    buttonLarge: 56,
    buttonCompact: 40,
    openingAvatar: 54,
    choiceChip: 38,
    buttonIconFrame: 26,
    iconButton: 36,
    header: 48,
    mobileHeader: 48,
    icon: 18,
    dockIcon: 24,
    coverWidth: 264,
    coverHeight: 352,
    listCoverHeight: 488,
    avatar: 112,
    identityAvatar: 84,
    authorAtmosphere: 485,
    creatorCompactHeader: 186,
    creatorCompactAvatar: 48,
    social: 38,
    socialGroupIcon: 28,
    statusDot: 6,
    fieldWidth: 366,
    dockIconHit: 44,
    phoneWidth: 390,
    dockReserve: 96,
    filterSortBar: 43,
    filterSortPill: 42,
    filterOption: 20,
    filterOptionRow: 38,
  },
  typography: {
    display: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 28,
      lineHeight: 32,
      letterSpacing: -1.12,
      fontWeight: '600' as const,
    },
    screenTitle: {
      fontFamily: 'Inter_500Medium',
      fontSize: 20,
      lineHeight: 26,
      letterSpacing: -0.2,
      fontWeight: '500' as const,
    },
    // Figma home headings `436:1275`: 24/29 semibold, -3% tracking.
    sectionTitle: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 24,
      lineHeight: 29,
      letterSpacing: -0.72,
      fontWeight: '600' as const,
    },
    cardTitle: {
      fontFamily: 'Inter_500Medium',
      fontSize: 18,
      lineHeight: 22,
      letterSpacing: -0.36,
      fontWeight: '500' as const,
    },
    body: {
      fontFamily: 'Inter_400Regular',
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '400' as const,
    },
    bodySmall: {
      fontFamily: 'Inter_400Regular',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: -0.14,
      fontWeight: '400' as const,
    },
    label: {
      fontFamily: 'Inter_500Medium',
      fontSize: 16,
      lineHeight: 26,
      letterSpacing: -0.32,
      fontWeight: '500' as const,
    },
    metadata: {
      fontFamily: 'Inter_500Medium',
      fontSize: 13,
      lineHeight: 16,
      letterSpacing: -0.13,
      fontWeight: '500' as const,
    },
    button: {
      fontFamily: 'Inter_500Medium',
      fontSize: 16,
      lineHeight: 26,
      letterSpacing: -0.32,
      fontWeight: '500' as const,
    },
    nav: {
      fontFamily: 'Inter_500Medium',
      fontSize: 16,
      lineHeight: 20,
      letterSpacing: -0.32,
      fontWeight: '500' as const,
    },
    caption: {
      fontFamily: 'Inter_400Regular',
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '400' as const,
    },
    numeric: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 18,
      lineHeight: 20,
      letterSpacing: -0.18,
      fontWeight: '600' as const,
    },
    field: {
      fontFamily: 'Inter_400Regular',
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '400' as const,
    },
    fieldLabel: {
      fontFamily: 'Inter_400Regular',
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '400' as const,
    },
    fieldError: {
      fontFamily: 'Inter_400Regular',
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '400' as const,
    },
    chip: {
      fontFamily: 'Inter_500Medium',
      fontSize: 13,
      lineHeight: 16,
      letterSpacing: -0.13,
      fontWeight: '500' as const,
    },
    choiceChip: {
      fontFamily: 'Inter_500Medium',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: -0.28,
      fontWeight: '500' as const,
    },
    coverTitle: {
      fontFamily: 'Inter_500Medium',
      fontSize: 18,
      lineHeight: 22,
      letterSpacing: -0.36,
      fontWeight: '500' as const,
    },
    coverPrice: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 18,
      lineHeight: 20,
      letterSpacing: -0.18,
      fontWeight: '600' as const,
    },
    coverMeta: {
      fontFamily: 'Inter_500Medium',
      fontSize: 15,
      lineHeight: 20,
      letterSpacing: -0.15,
      fontWeight: '500' as const,
    },
    authorName: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 22,
      lineHeight: 24,
      letterSpacing: -0.66,
      fontWeight: '600' as const,
    },
    authorHandle: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 18,
      lineHeight: 20,
      letterSpacing: -0.18,
      fontWeight: '600' as const,
    },
    // Home opening handle `439:4414`: Inter Medium 22/25, tracking -1%.
    authorRowHandle: {
      fontFamily: 'Inter_500Medium',
      fontSize: 22,
      lineHeight: 25,
      letterSpacing: -0.22,
      letterSpacingEm: '-0.01em',
      fontWeight: '500' as const,
    },
    // Home opening bio `439:4415`: Inter Regular 14 / box 17, `#6F6F6F`.
    authorRowBio: {
      fontFamily: 'Inter_400Regular',
      fontSize: 14,
      lineHeight: 17,
      fontWeight: '400' as const,
    },
    // Home curator heading `439:4417`: Inter Medium 20 / box 24, tracking -2%.
    editorialTitle: {
      fontFamily: 'Inter_500Medium',
      fontSize: 20,
      lineHeight: 24,
      letterSpacing: -0.4,
      letterSpacingEm: '-0.02em',
      fontWeight: '500' as const,
    },
    // Home curator note `439:4418`: Inter Regular 16/22, tracking -1%.
    editorial: {
      fontFamily: 'Inter_400Regular',
      fontSize: 16,
      lineHeight: 22,
      letterSpacing: -0.16,
      letterSpacingEm: '-0.01em',
      fontWeight: '400' as const,
    },
    // Home profile pill label `439:4420`: Inter Medium 13/18, tracking -1%.
    buttonCompact: {
      fontFamily: 'Inter_500Medium',
      fontSize: 13,
      lineHeight: 18,
      letterSpacing: -0.13,
      letterSpacingEm: '-0.01em',
      fontWeight: '500' as const,
    },
    workTitle: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 20,
      lineHeight: 24,
      letterSpacing: -0.4,
      fontWeight: '600' as const,
    },
    workAuthor: {
      fontFamily: 'Inter_400Regular',
      fontSize: 16,
      lineHeight: 19,
      letterSpacing: -0.16,
      fontWeight: '400' as const,
    },
    workChip: {
      fontFamily: 'Inter_500Medium',
      fontSize: 14,
      lineHeight: 17,
      letterSpacing: -0.14,
      fontWeight: '500' as const,
    },
    profileHandle: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 24,
      lineHeight: 29,
      letterSpacing: -0.72,
      fontWeight: '600' as const,
    },
    profileHandleCompact: {
      fontFamily: 'Inter_500Medium',
      fontSize: 16,
      lineHeight: 19,
      letterSpacing: -0.32,
      fontWeight: '500' as const,
    },
    profileMetadata: {
      fontFamily: 'Inter_500Medium',
      fontSize: 18,
      lineHeight: 24,
      letterSpacing: -0.18,
      fontWeight: '500' as const,
    },
    profileChip: {
      fontFamily: 'Inter_500Medium',
      fontSize: 16,
      lineHeight: 23,
      letterSpacing: -0.16,
      fontWeight: '500' as const,
    },
    profileTab: {
      fontFamily: 'Inter_500Medium',
      fontSize: 16,
      lineHeight: 19,
      letterSpacing: -0.32,
      fontWeight: '500' as const,
    },
    profileTabCount: {
      fontFamily: 'Inter_400Regular',
      fontSize: 12,
      lineHeight: 14,
      letterSpacing: -0.24,
      fontWeight: '400' as const,
    },
    profileHeading: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 17,
      lineHeight: 21,
      letterSpacing: -0.34,
      fontWeight: '600' as const,
    },
    achievementStatement: {
      fontFamily: 'Inter_500Medium',
      fontSize: 20,
      lineHeight: 28,
      fontWeight: '500' as const,
    },
    achievementDate: {
      fontFamily: 'Inter_500Medium',
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '500' as const,
    },
    identityHandle: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 28,
      lineHeight: 32,
      letterSpacing: -1.12,
      fontWeight: '600' as const,
    },
    identityRowHandle: {
      fontFamily: 'Inter_600SemiBold',
      fontSize: 24,
      lineHeight: 25,
      letterSpacing: -0.24,
      fontWeight: '600' as const,
    },
  },
  motion: {
    instant: 80,
    fast: 160,
    control: 200,
    media: 300,
    panelOpen: 220,
    panelClose: 150,
    layout: 260,
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
  },
  layout: {
    contentMaxWidth: 390,
    headerMaxWidth: 390,
    discoveryMaxWidth: 390,
    productDetailMaxWidth: 390,
    productHeroContentWidth: 390,
    desktopGutter: 12,
    creatorDesktopGutter: 12,
    tabletGutter: 12,
    mobileGutter: 12,
    cardWidth: 366,
    discoveryMenuWidth: 240,
    accountPopoverWidth: 280,
    mobileMenuWidth: 320,
    dialogMaxWidth: 366,
    phoneWidth: 390,
    openingAuthorWidth: 280,
    phoneFoldHeight: 860,
  },
  breakpoint: {
    mobileHeader: 99999,
    desktopShell: 99999,
    compactHeader: 99999,
    headerSearchInline: 99999,
    catalogTwoColumn: 99999,
    productDetailWide: 99999,
    productHeroThreeColumn: 99999,
    catalogThreeColumn: 99999,
    catalogFourColumn: 99999,
  },
  ratio: {
    productPortrait: 264 / 352,
    auctionCardMedia: 264 / 352,
  },
  productHeroWide: 366,
  elevation: {
    floating: {
      boxShadow: '0 10px 24px rgba(17, 17, 17, 0.12)',
    },
  },
  layer: { content: 0, chrome: 10, popover: 20, modal: 50 },
  focus: { width: 2, offset: 2 },
  blur: {
    dock: 6,
    dockNativeIntensity: 30,
    dockAndroidReductionFactor: 5,
    overlay: 30,
    authorTopOverlay: 20,
    atmosphere: 40,
  },
  opacity: {
    disabled: 0.5,
    atmosphere: 0.5,
    quietBorder: 0.16,
  },
  stroke: {
    icon: 1.13,
    iconHeavy: 1.25,
    dockIcon: 1.5,
  },
} as const;

export const figmaTokens = designTokens;

export type TextRole = keyof typeof designTokens.typography;
export type FigmaTokens = typeof designTokens;

type TypographyRole = (typeof designTokens.typography)[TextRole];

export function typographyLetterSpacingEm(role: TextRole) {
  const spec = designTokens.typography[role] as TypographyRole & {
    letterSpacingEm?: string;
  };
  return spec.letterSpacingEm;
}
