import { type ProductWriteRequest } from '@bidplace/contracts';
import { type Prisma } from '@bidplace/database';
import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../core/database'; import { PublicIdService } from '../core/public-id'; import { productSelect, toProductResponse } from './products.mapper';
const lockedStatuses = ['SCHEDULED', 'LIVE'] as const;
@Injectable()
export class ProductsService {
  constructor(private readonly prisma: PrismaService, private readonly publicIds: PublicIdService) {}
  async create(userId: string, input: ProductWriteRequest) { const seller = await this.prisma.sellerProfile.findUnique({ where: { userId }, select: { id: true } }); if (!seller) throw new NotFoundException('Seller profile not found'); return this.createWithPublicId(seller.id, input); }
  private async createWithPublicId(sellerProfileId: string, input: ProductWriteRequest) { for (let attempt = 0; attempt < 5; attempt += 1) { try { const data: Prisma.ProductUncheckedCreateInput = { sellerProfileId, publicId: this.publicIds.generate(), categoryId: input.categoryId ?? null, title: input.title ?? null, story: input.story ?? null, technique: input.technique ?? null, materials: input.materials ?? null, dimensions: input.dimensions ?? null, weight: input.weight ?? null, year: input.year ?? null, condition: input.condition ?? null, uniqueness: input.uniqueness ?? null, provenance: input.provenance ?? null, city: input.city ?? null, deliveryInfo: input.deliveryInfo ?? null }; const product = await this.prisma.product.create({ data, select: productSelect }); return toProductResponse(product); } catch (error) { if (!(typeof error === 'object' && error !== null && 'code' in error && error.code === 'P2002')) throw error; } } throw new ConflictException('Could not assign public identifier'); }
  async update(userId: string, id: string, input: ProductWriteRequest) { const product = await this.prisma.product.findUnique({ where: { id }, select: { sellerProfile: { select: { userId: true } }, listings: { where: { status: { in: [...lockedStatuses] } }, select: { id: true }, take: 1 } } }); if (!product) throw new NotFoundException('Product not found'); if (product.sellerProfile.userId !== userId) throw new ForbiddenException('Product is not owned by user'); if (product.listings.length) throw new ConflictException('Product is locked by an active Listing'); const data: Prisma.ProductUncheckedUpdateInput = {}; if (input.categoryId !== undefined) data.categoryId = input.categoryId; if (input.title !== undefined) data.title = input.title; if (input.story !== undefined) data.story = input.story; if (input.technique !== undefined) data.technique = input.technique; if (input.materials !== undefined) data.materials = input.materials; if (input.dimensions !== undefined) data.dimensions = input.dimensions; if (input.weight !== undefined) data.weight = input.weight; if (input.year !== undefined) data.year = input.year; if (input.condition !== undefined) data.condition = input.condition; if (input.uniqueness !== undefined) data.uniqueness = input.uniqueness; if (input.provenance !== undefined) data.provenance = input.provenance; if (input.city !== undefined) data.city = input.city; if (input.deliveryInfo !== undefined) data.deliveryInfo = input.deliveryInfo; const updated = await this.prisma.product.update({ where: { id }, data, select: productSelect }); return toProductResponse(updated); }
  async getPublic(publicId: string) { const product = await this.prisma.product.findFirst({ where: { publicId, status: 'APPROVED' }, select: productSelect }); if (!product) throw new NotFoundException('Product not found'); return toProductResponse(product); }
}
