import { publicProductDetailResponseSchema, productListResponseSchema, type PaginationQuery, type ProductWriteRequest } from '@bidplace/contracts';
import { type Prisma } from '@bidplace/database';
import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../core/database'; import { resolveMinimumNextBid } from '../core/auction'; import { PublicIdService } from '../core/public-id'; import { productSelect, toProductResponse } from './products.mapper';
const lockedStatuses = ['SCHEDULED', 'LIVE'] as const;
@Injectable()
export class ProductsService {
  constructor(private readonly prisma: PrismaService, private readonly publicIds: PublicIdService) {}
  async create(userId: string, input: ProductWriteRequest) { const seller = await this.prisma.sellerProfile.findUnique({ where: { userId }, select: { id: true } }); if (!seller) throw new NotFoundException('Seller profile not found'); return this.createWithPublicId(seller.id, input); }
  private async createWithPublicId(sellerProfileId: string, input: ProductWriteRequest) { for (let attempt = 0; attempt < 5; attempt += 1) { try { const data: Prisma.ProductUncheckedCreateInput = { sellerProfileId, publicId: this.publicIds.generate(), categoryId: input.categoryId ?? null, title: input.title ?? null, story: input.story ?? null, technique: input.technique ?? null, materials: input.materials ?? null, dimensions: input.dimensions ?? null, weight: input.weight ?? null, year: input.year ?? null, condition: input.condition ?? null, uniqueness: input.uniqueness ?? null, provenance: input.provenance ?? null, city: input.city ?? null, deliveryInfo: input.deliveryInfo ?? null }; const product = await this.prisma.product.create({ data, select: productSelect }); return toProductResponse(product); } catch (error) { if (!(typeof error === 'object' && error !== null && 'code' in error && error.code === 'P2002')) throw error; } } throw new ConflictException('Could not assign public identifier'); }
  async update(userId: string, id: string, input: ProductWriteRequest) { const product = await this.prisma.product.findUnique({ where: { id }, select: { sellerProfile: { select: { userId: true } }, listings: { where: { status: { in: [...lockedStatuses] } }, select: { id: true }, take: 1 } } }); if (!product) throw new NotFoundException('Product not found'); if (product.sellerProfile.userId !== userId) throw new ForbiddenException('Product is not owned by user'); if (product.listings.length) throw new ConflictException('Product is locked by an active Listing'); const data: Prisma.ProductUncheckedUpdateInput = {}; if (input.categoryId !== undefined) data.categoryId = input.categoryId; if (input.title !== undefined) data.title = input.title; if (input.story !== undefined) data.story = input.story; if (input.technique !== undefined) data.technique = input.technique; if (input.materials !== undefined) data.materials = input.materials; if (input.dimensions !== undefined) data.dimensions = input.dimensions; if (input.weight !== undefined) data.weight = input.weight; if (input.year !== undefined) data.year = input.year; if (input.condition !== undefined) data.condition = input.condition; if (input.uniqueness !== undefined) data.uniqueness = input.uniqueness; if (input.provenance !== undefined) data.provenance = input.provenance; if (input.city !== undefined) data.city = input.city; if (input.deliveryInfo !== undefined) data.deliveryInfo = input.deliveryInfo; const updated = await this.prisma.product.update({ where: { id }, data, select: productSelect }); return toProductResponse(updated); }
  async getPublic(publicId: string) { const product = await this.prisma.product.findFirst({ where: { publicId, status: 'APPROVED' }, include: { sellerProfile: true, images: { orderBy: { position: 'asc' } }, listings: { where: { status: { in: ['SCHEDULED', 'LIVE', 'ENDED'] } }, include: { auctionRules: true }, orderBy: { createdAt: 'desc' }, take: 1 } } }); if (!product) throw new NotFoundException('Product not found'); const projection = this.toPublicProduct(product); const currentListing = product.listings[0]; return publicProductDetailResponseSchema.parse({ ...projection, minimumNextBid: projection.listing?.status === 'LIVE' && currentListing ? resolveMinimumNextBid(currentListing.currentPrice).toNumber() : null }); }
  async listPublic(query: PaginationQuery) { const where = { status: 'APPROVED' as const }; const [products, total] = await Promise.all([this.prisma.product.findMany({ where, include: { sellerProfile: true, images: { orderBy: { position: 'asc' } }, listings: { where: { status: { in: ['SCHEDULED', 'LIVE'] } }, include: { auctionRules: true }, take: 1 } }, orderBy: { createdAt: 'desc' }, skip: (query.page - 1) * query.limit, take: query.limit }), this.prisma.product.count({ where })]); return productListResponseSchema.parse({ products: products.map((product) => this.toPublicProduct(product)), pagination: { ...query, total } }); }
  toPublicProduct(product: Awaited<ReturnType<PrismaService['product']['findFirst']>> & object) { const record = product as typeof product & { sellerProfile: { id: string; userId: string; slug: string; sellerType: 'creator' | 'influencer'; storeName: string; country: string; contactPreference: string; socialLink: string | null; shortDescription: string | null; status: 'DRAFT' | 'APPROVED' | 'SUSPENDED'; createdAt: Date; updatedAt: Date }; images: Array<{ id: string; position: number; mimeType: string; byteLength: number; checksum: string }>; listings: Array<{ id: string; productId: string; type: 'AUCTION'; status: 'DRAFT' | 'SCHEDULED' | 'LIVE' | 'ENDED' | 'CANCELLED'; currency: string; startsAt: Date; originalEndsAt: Date; endsAt: Date; currentPrice: { toNumber(): number }; bidCount: number; closedAt: Date | null; createdAt: Date; updatedAt: Date; auctionRules: { startPrice: { toNumber(): number }; incrementPolicyCode: string; softCloseWindowSeconds: number; softCloseExtensionSeconds: number; softCloseMaxTotalSeconds: number } | null }> }; const listing = record.listings[0] ?? null; return { product: { ...toProductResponse({ ...record, images: record.images }).product }, sellerProfile: { slug: record.sellerProfile.slug, sellerType: record.sellerProfile.sellerType, storeName: record.sellerProfile.storeName, country: record.sellerProfile.country, contactPreference: record.sellerProfile.contactPreference, socialLink: record.sellerProfile.socialLink, shortDescription: record.sellerProfile.shortDescription }, listing: listing && listing.auctionRules ? { id: listing.id, productId: listing.productId, type: 'AUCTION' as const, status: listing.status, currency: 'BYN' as const, startsAt: listing.startsAt.toISOString(), originalEndsAt: listing.originalEndsAt.toISOString(), endsAt: listing.endsAt.toISOString(), currentPrice: listing.currentPrice.toNumber(), bidCount: listing.bidCount, closedAt: listing.closedAt?.toISOString() ?? null, createdAt: listing.createdAt.toISOString(), updatedAt: listing.updatedAt.toISOString(), auctionRules: { startPrice: listing.auctionRules.startPrice.toNumber(), incrementPolicyCode: 'MVP_BYN_V1' as const, softCloseWindowSeconds: 60 as const, softCloseExtensionSeconds: 60 as const, softCloseMaxTotalSeconds: 600 as const } } : null }; }
}
